dice_website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
]

projects/urls.py
from django.urls import path
from projects import views

urlpatterns = [
    path('', views.projects, name='projects'),
    path('dice/', views.shop, name='shop_page'),
    path('dice/<int:pk>/', views.dice_page, name='dice_page'),
    path('about/', views.about_page, name="about")
]

projects/models.py
from django.db import models

class Image(models.Model):
    url = models.CharField(max_length=255)
    dice = models.ForeignKey('Dice', on_delete=models.CASCADE)

class Dice(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    sold = models.BooleanField()

projects/views.py
from django.shortcuts import render
from projects.models import Dice, Image

# Create your views here.
def projects(request):
    dice = Dice.objects.all()[:3]
    images = Image.objects.all()
    context = {
        "dice": dice,
        "images": images
    }
    return render(request, 'index.html', context)

# TODO: Make each page dynamic based on the dice given
def dice_page(request, pk):
    dice = Dice.objects.get(pk=pk)
    images = Image.objects.filter(dice_id=pk)
    context = {
        "dice": dice,
        "images": images
    }
    return render(request, "dice_page.html", context)

def shop(request):
    dice = Dice.objects.all()
    images = Image.objects.all()
    context = {
        "dice": dice,
        "images": images
    }
    return render(request, "shop.html", context)

def about_page(request):
    return render(request, "about.html")

projects/templates/about.html
{% extends "base.html" %} {% block content %}

<section>
    <h1>About Tressym Dice</h1>
</section>

<section>
    <p>Hi! I'm Rachel and I like to make dice for TTRPG games including Dungeons & Dragons and Pathfinder. They are made using epoxy resin, dyes, and whatever fun things I can think of putting inside. </p>
    <p>As these are handmade dice, some defects may be present but they will not affect playability. I will provide pictures showing any known defects in the die, and they will be marked down in price accordingly.</p>
</section>

{% endblock %}

projects/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tressym Dice</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/css/style.css' %}">
    <script src="{% static 'javascript/script.js' %}" defer></script>
</head>

<body>
    <header>
        <img src="{% static 'images/tressym_dice_transparent.jpg' %}" alt="Tressym Dice Logo">
        <nav>
            <div id="links">
                <a href="/">Home</a>
                <a href="/dice">Store</a>
                <a href="/about">About</a>
                <!-- <a href="#contact">Contact</a> -->
            </div>
            <a href="javascript:void(0);" class="icon" onclick="openHamburger()">&#8801;</a>
        </nav>
    </header>
    <div class="body_content">
        {% block content %} {% endblock %}
    </div>
    <footer>
        <p>Copyright &copy; Tressym Dice 2022</p>
        <p><a href="https://www.instagram.com/tressym.dice/" target="_blank">Instagram</a></p>
    </footer>
</body>

</html>

projects/templates/dice_page.html
{% extends "base.html" %} {% block content %}

<section class="product">
    <h1 class="dice_name">{{dice.name}}{% if dice.sold %} - Sold{% endif %}</h1>
    <p class="dice_description">{{dice.description}}</p>
    <button class="cart" {% if dice.sold %}disabled{% endif %}>Add to Cart</button>
    <div class="img_container">
        {% for image in images %}
        <img class="dice_img" src="../../static/{{ image.url }}"> {% endfor %}
    </div>
</section>

{% endblock %}

projects/templates/index.html
{% extends "base.html" %} {% block content %}

<section>
    <h1>Hello!</h1>
    <p>Welcome to Tressym Dice. I make handmade dice to be used in tabletop RPG games. </p>
</section>

<section>
    <h1>Featured Products</h1>
</section>



<div class="card_container">
    {% for dice_set in dice %}
    <section class="dice_card">
        {% with dice_set.image_set.all|first as image %}
        <a href="{% url 'dice_page' dice_set.pk %}">
            <img class="dice_img" src="static/{{ image.url }}"> {% endwith %}
            <h2 class="dice_card">{{dice_set.name}}</h2>
            <p class="dice_card">${{dice_set.price}}</p>
        </a>
    </section>
    {% endfor %}
</div>


{% endblock %}

projects/templates/shop.html
{% extends "base.html" %} {% block content %}

<section>
    <h1>Products</h1>
</section>

<section>
    <div class="card_container">
        {% for dice_set in dice %}
        <section class="dice_card">
            {% with dice_set.image_set.all|first as image %}
            <a href="{% url 'dice_page' dice_set.pk %}">
                <img class="dice_img {% if dice_set.sold %}sold{% endif %}" src="../static/{{ image.url }}"> {% endwith %}
                <h2 class="dice_card">{{dice_set.name}} {% if dice_set.sold %} - Sold {% endif %}</h2>
                <p class="dice_card">${{dice_set.price}}</p>
            </a>
        </section>
        {% endfor %}
    </div>
</section>

{% endblock %}